import PDFDocument from 'pdfkit';
import { ExportDefinition } from './types';
import { formatValue } from './helpers';
import { Writable } from 'stream';

export const buildPDF = <T = any>(
  definition: ExportDefinition<T>,
  stream: Writable
): void => {
  // Use A4 landscape for wide tabular business data exports
  const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 28, bufferPages: true });
  doc.pipe(stream);

  const pageLeft = doc.page.margins.left;
  const contentWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  // Calculate proportional column widths filling 100% of contentWidth
  let totalWidthWeight = 0;
  definition.columns.forEach(c => { totalWidthWeight += c.width || 15; });
  
  const columns = definition.columns.map(c => ({
    ...c,
    pdfWidth: ((c.width || 15) / totalWidthWeight) * contentWidth
  }));

  const drawTableHeader = () => {
    const y = doc.y;
    doc.rect(pageLeft, y, contentWidth, 22).fill('#0f766e'); // Teal-700
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#ffffff');
    let x = pageLeft;
    columns.forEach((col) => {
      doc.text(col.header, x + 3, y + 6, { width: col.pdfWidth - 6, align: col.align || 'left' });
      x += col.pdfWidth;
    });
    doc.y = y + 22;
  };

  const drawCell = (text: string, x: number, y: number, width: number, height: number, options: PDFKit.Mixins.TextOptions = {}) => {
    doc.rect(x, y, width, height).stroke('#e2e8f0');
    doc.text(text, x + 3, y + 5, {
      width: width - 6,
      height: height - 8,
      ellipsis: true,
      ...options
    });
  };

  const ensureSpace = (neededHeight: number) => {
    if (doc.y + neededHeight <= doc.page.height - doc.page.margins.bottom - 20) return;
    doc.addPage();
    drawTableHeader();
  };

  // Header Banner Section
  if (definition.metadata.firmName) {
    doc.font('Helvetica-Bold').fontSize(16).fillColor('#0f172a')
       .text(definition.metadata.firmName, { align: 'center' });
    doc.moveDown(0.2);
  }
  doc.font('Helvetica-Bold').fontSize(13).fillColor('#1e293b')
     .text(definition.title, { align: 'center' });
  doc.moveDown(0.3);

  // Metadata Subtitle
  const metaParts = [
    `Generated on: ${formatValue(definition.metadata.generatedAt, 'datetime')}`,
    `Generated by: ${definition.metadata.generatedBy}`
  ];

  if (definition.metadata.filters && Object.keys(definition.metadata.filters).length > 0) {
    const filterText = Object.entries(definition.metadata.filters)
      .map(([k, v]) => `${k}: ${v}`)
      .join(' | ');
    metaParts.push(`Filters: ${filterText}`);
  }

  doc.font('Helvetica').fontSize(8).fillColor('#64748b')
     .text(metaParts.join('  •  '), { align: 'center' });
  
  doc.moveDown(1.2);

  // Render Table
  drawTableHeader();

  definition.dataRows.forEach((row, index) => {
    ensureSpace(22);
    const y = doc.y;
    
    // Alternating row background
    if (index % 2 === 0) {
      doc.rect(pageLeft, y, contentWidth, 22).fill('#f8fafc');
    }

    doc.font('Helvetica').fontSize(8).fillColor('#0f172a');
    let x = pageLeft;
    
    columns.forEach((col) => {
      const rawValue = row[col.key as keyof T];
      const formatted = col.format ? formatValue(rawValue, col.format) : formatValue(rawValue);
      drawCell(formatted, x, y, col.pdfWidth, 22, { align: col.align || 'left' });
      x += col.pdfWidth;
    });

    doc.y = y + 22;
  });

  // Summary KPIs Box at the end of the report
  if (definition.summary && definition.summary.length > 0) {
    ensureSpace(60);
    doc.moveDown(0.8);
    const summaryBoxY = doc.y;
    const summaryBoxWidth = Math.min(contentWidth, 420);
    const summaryBoxX = pageLeft + contentWidth - summaryBoxWidth; // align right

    doc.rect(summaryBoxX, summaryBoxY, summaryBoxWidth, 20 + definition.summary.length * 16).fill('#f1f5f9');
    doc.rect(summaryBoxX, summaryBoxY, summaryBoxWidth, 20 + definition.summary.length * 16).stroke('#cbd5e1');

    doc.font('Helvetica-Bold').fontSize(8.5).fillColor('#0f172a')
       .text('EXECUTIVE SUMMARY / KEY METRICS', summaryBoxX + 8, summaryBoxY + 5, { width: summaryBoxWidth - 16 });

    let currentItemY = summaryBoxY + 20;
    definition.summary.forEach(item => {
      doc.font('Helvetica').fontSize(8).fillColor('#475569')
         .text(item.label, summaryBoxX + 8, currentItemY, { width: summaryBoxWidth * 0.6 });
      
      const formattedVal = item.format ? formatValue(item.value, item.format) : String(item.value);
      doc.font('Helvetica-Bold').fontSize(8).fillColor('#059669')
         .text(formattedVal, summaryBoxX + summaryBoxWidth * 0.6, currentItemY, { width: summaryBoxWidth * 0.38, align: 'right' });
      
      currentItemY += 16;
    });
  }

  // Global Page Footer with Numbering ("Page X of Y")
  const pages = doc.bufferedPageRange();
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(i);
    doc.font('Helvetica').fontSize(8).fillColor('#94a3b8')
       .text(
         `Page ${i + 1} of ${pages.count}`,
         pageLeft,
         doc.page.height - 22,
         { align: 'center', width: contentWidth }
       );
  }

  doc.end();
};
