import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import {
  ArrowLeft, Shield, Lock, Database, Users, Eye, Server,
  Cookie, Clock, Share2, Globe, FileText, UserCheck,
  ShieldCheck, HardDrive, Trash2, Bell, Mail, Heart,
  Gift, Truck, Package, ShoppingCart, Layers, BarChart3
} from 'lucide-react';

const sections = [
  {
    id: 'introduction',
    num: '1',
    title: 'Introduction',
    icon: Shield,
    color: 'from-blue-500 to-accent2-500',
    content: (
      <>
        <p>Welcome to <strong>Bharat Enterprise Billing System</strong> ("Platform", "we", "us", or "our"). We are a cloud-based, multi-tenant billing, inventory, purchasing, and business management platform designed for pharmaceutical distributors, retailers, wholesalers, and small-to-medium businesses across India.</p>
        <p>We are dedicated to safeguarding the privacy and security of your commercial and personal data. This Privacy Policy explains what information we process, why we process it, how we protect it, and the controls you have over your data.</p>
        <p>By registering for an account or using our Platform, you acknowledge the data processing practices described in this Privacy Policy. If you do not agree, please discontinue using the Platform.</p>
        <p>This policy is formulated in straightforward language so that business owners and their operational teams can clearly understand how business information is managed.</p>
      </>
    )
  },
  {
    id: 'information-we-collect',
    num: '2',
    title: 'Information We Collect & Process',
    icon: Database,
    color: 'from-emerald-500 to-teal-500',
    content: (
      <>
        <p>We collect and process only the information necessary to provide you with a reliable billing, invoicing, purchasing, inventory management, and operational reporting experience.</p>

        <h4>2.1 Account & Authentication Information</h4>
        <ul>
          <li>Full name, official email address, and contact phone number.</li>
          <li>Registered business name, trade name, and commercial address.</li>
          <li>Encrypted account credentials (passwords hashed using industry-standard bcrypt; never stored in plaintext).</li>
          <li>Account designation and access tier (Admin or Employee).</li>
        </ul>

        <h4>2.2 Customer & Ledger Data</h4>
        <ul>
          <li>Customer/client business names, billing/shipping addresses, phone numbers, email addresses, and GSTIN.</li>
          <li>Customer ledger entries, receipts, balance adjustments, and outstanding payment records.</li>
        </ul>

        <h4>2.3 Supplier Data</h4>
        <ul>
          <li>Supplier vendor business names, contact persons, phone numbers, and email addresses.</li>
          <li>Supplier billing addresses, GSTIN numbers, state codes, payment terms, opening balances, and vendor notes.</li>
          <li>Supplier data is entered and managed directly by your organization for inward procurement tracking.</li>
        </ul>

        <h4>2.4 Purchase & Inward Stock Data</h4>
        <ul>
          <li>Purchase invoice numbers, inward reference identifiers, and purchase dates.</li>
          <li>Line item product details, invoiced quantities, free promotional quantities, purchase rates, selling rates, and MRP.</li>
          <li>Batch lot numbers, manufacturing dates, and expiry dates.</li>
          <li>Applicable tax rates (CGST, SGST, IGST), taxable amounts, discounts, and invoice totals.</li>
        </ul>

        <h4>2.5 Inventory, Batch & Movement Data</h4>
        <ul>
          <li>Warehouse stock quantities and product catalog configurations (standard or batch-enabled).</li>
          <li>Batch records, lot numbers, received dates, and expiry timelines.</li>
          <li>Immutable StockMovement transaction ledger entries recording stock additions (purchases), deductions (sales invoices), returns (credit notes), and manual inventory adjustments.</li>
        </ul>

        <h4>2.6 Invoice, Payment & Credit Note Data</h4>
        <ul>
          <li>Tax invoices, proforma bills, credit notes, itemized rates, discounts, and GST breakdowns.</li>
          <li>Internal customer payment records, payment modes (Cash, Bank Transfer, UPI, Cheque), and receipt timestamps.</li>
        </ul>

        <h4>2.7 Employee & Role-Based Access (RBAC) Data</h4>
        <ul>
          <li>Employee user profiles, contact details, assigned system roles, and assigned granular module permissions.</li>
          <li>Activity and audit logs documenting employee actions within the tenant (e.g., transaction creation, modification, or cancellation) to preserve administrative traceability.</li>
        </ul>

        <h4>2.8 Subscription & Billing Data</h4>
        <ul>
          <li>Active subscription plan (Starter, Business, or Professional), billing frequency, and validity period.</li>
          <li>Payment transaction references and timestamps generated by our secure third-party payment gateway partner.</li>
          <li>Free trial, grace period, and plan upgrade/downgrade history.</li>
        </ul>

        <h4>2.9 Referral Program Data</h4>
        <ul>
          <li>Unique referral codes and shareable links generated for your account.</li>
          <li>Referral conversion statuses and credited reward days.</li>
        </ul>

        <h4>2.10 Technical, Browser & Device Information</h4>
        <ul>
          <li>IP address, browser type and version, operating system, and hardware concurrency indicators utilized for lightweight performance optimizations.</li>
          <li>Application error logs, system diagnostics, and operational performance metrics.</li>
        </ul>

        <div className="pp-callout">
          <strong>No Payment Card Storage:</strong> We do <strong>not</strong> collect or store credit card numbers, debit card numbers, CVVs, net banking credentials, or UPI PINs. All platform subscription billing is processed directly through secure, PCI-DSS compliant payment gateway infrastructure.
        </div>
      </>
    )
  },
  {
    id: 'how-we-use-information',
    num: '3',
    title: 'How We Use Your Information',
    icon: Eye,
    color: 'from-accent-500 to-accent-500',
    content: (
      <>
        <p>We process your business and account data strictly for legitimate operational and business purposes, including:</p>
        <ul>
          <li><strong>Service Delivery</strong> — Providing core billing, tax invoicing, customer ledger tracking, credit note generation, and GST-related reporting tools.</li>
          <li><strong>Inventory & Batch Management</strong> — Tracking real-time warehouse stock, managing batch lots, executing automated FIFO allocation, and maintaining the inventory movement audit trail.</li>
          <li><strong>Purchase & Supplier Processing</strong> — Managing inward supplier bills, tracking vendor balances, updating stock on purchase completion, and recording stock reversals upon purchase cancellation.</li>
          <li><strong>Operational Reporting & Intelligence</strong> — Generating purchase summaries, movement history, supplier procurement activity, and inventory intelligence insights.</li>
          <li><strong>Access Control & Team Management</strong> — Enforcing tenant isolation and role-based employee permissions configured by organization Admins.</li>
          <li><strong>Account & Subscription Administration</strong> — Managing trial access, billing cycles, renewals, plan transitions, and referral rewards.</li>
          <li><strong>Platform Reliability & Security</strong> — Monitoring platform health, diagnosing errors, preventing unauthorized multi-tenant access, and deterring fraudulent activity.</li>
          <li><strong>Service Communications</strong> — Delivering essential administrative notifications, security alerts, policy updates, and subscription status reminders.</li>
        </ul>
        <p>We do <strong>not</strong> sell, rent, monetize, or trade your personal or business data to third parties for advertising or marketing purposes.</p>
      </>
    )
  },
  {
    id: 'multi-tenant-isolation',
    num: '4',
    title: 'Multi-Tenant Data Isolation & Security',
    icon: Lock,
    color: 'from-amber-500 to-orange-500',
    content: (
      <>
        <p>The Platform employs a <strong>multi-tenant cloud architecture</strong> designed with strict logical segregation:</p>
        <ul>
          <li><strong>Tenant-Scoped Queries</strong> — Every backend API request, database query, and reporting computation is strictly scoped to the authenticated user's organization identifier. No tenant can view, access, or modify another tenant's records.</li>
          <li><strong>Tenant-Scoped Unique Constraints</strong> — Database indexes for customer numbers, invoice identifiers, and product codes are enforced per tenant, preventing cross-tenant data exposure.</li>
          <li><strong>Admin Organization Ownership</strong> — All commercial data belongs to the organization (tenant Admin), not to individual employee users.</li>
          <li><strong>Continuous Security Verification</strong> — Our authorization layers are structured to ensure that tenant context cannot be spoofed or bypassed.</li>
        </ul>
      </>
    )
  },
  {
    id: 'authentication',
    num: '5',
    title: 'Authentication & Access Control',
    icon: ShieldCheck,
    color: 'from-cyan-500 to-blue-500',
    content: (
      <>
        <ul>
          <li><strong>Encrypted Passwords</strong> — All passwords are encrypted with bcrypt using strong salt factors and are never stored in readable plaintext.</li>
          <li><strong>Token-Based Authentication</strong> — User sessions are authenticated using secure JSON Web Tokens (JWT) that expire automatically upon inactivity.</li>
          <li><strong>Role-Based Permission Middleware</strong> — All backend endpoints verify that the requesting user holds the specific permission required for the requested action.</li>
        </ul>
      </>
    )
  },
  {
    id: 'data-storage',
    num: '6',
    title: 'Cloud Infrastructure & Third-Party Service Providers',
    icon: Server,
    color: 'from-rose-500 to-pink-500',
    content: (
      <>
        <p>Your data is securely hosted and processed using reputable, enterprise-grade cloud service providers:</p>
        <div className="pp-table-wrap">
          <table>
            <thead>
              <tr>
                <th>Infrastructure Component</th>
                <th>Provider</th>
                <th>Functional Purpose</th>
              </tr>
            </thead>
            <tbody>
              <tr><td>Database & Document Storage</td><td>MongoDB Atlas</td><td>Encrypted cloud database storing application records</td></tr>
              <tr><td>Frontend Application Hosting</td><td>Vercel</td><td>Global edge CDN serving the web application</td></tr>
              <tr><td>Backend API Server</td><td>Render</td><td>Cloud server executing application logic and APIs</td></tr>
              <tr><td>Subscription Payment Processing</td><td>Authorized Payment Gateway</td><td>PCI-DSS certified gateway for SaaS subscription payments</td></tr>
            </tbody>
          </table>
        </div>
        <p>All cloud infrastructure providers enforce encryption in transit (TLS/HTTPS) and adhere to rigorous international security and availability standards.</p>
      </>
    )
  },
  {
    id: 'cookies',
    num: '7',
    title: 'Cookies & Browser Storage Handling',
    icon: Cookie,
    color: 'from-yellow-500 to-amber-500',
    content: (
      <>
        <ul>
          <li><strong>Authentication Tokens</strong> — Secure storage of session tokens necessary to keep you authenticated across requests.</li>
          <li><strong>User Interface Preferences</strong> — Browser local storage for theme choices, collapsed sidebar states, and table column visibility.</li>
          <li><strong>Form Session Recovery</strong> — Temporary browser session storage to prevent loss of in-progress invoice or purchase entries during active typing.</li>
        </ul>
        <p>We do <strong>not</strong> deploy third-party advertising cookies, behavioural retargeting pixels, or marketing trackers.</p>
      </>
    )
  },
  {
    id: 'data-retention',
    num: '8',
    title: 'Data Retention & Deletion',
    icon: Clock,
    color: 'from-accent2-500 to-accent-500',
    content: (
      <>
        <ul>
          <li><strong>Active Subscriptions</strong> — All business data (products, customers, suppliers, purchases, invoices, stock movements) is retained for the duration of your active account.</li>
          <li><strong>Subscription Downgrades</strong> — Downgrading subscription tiers adjusts access to higher-tier features, but does <strong>not</strong> delete historical transactions, invoices, purchases, or ledger entries.</li>
          <li><strong>Account Closure</strong> — Upon explicit request for account termination, tenant data is scheduled for permanent deletion from active databases within <strong>90 days</strong>, subject to statutory retention obligations.</li>
          <li><strong>Disaster Recovery Backups</strong> — Periodic automated cloud database snapshots may persist temporarily in disaster recovery archives until cycled out in accordance with standard backup rotation schedules.</li>
        </ul>
      </>
    )
  },
  {
    id: 'data-sharing',
    num: '9',
    title: 'Data Sharing Policy',
    icon: Share2,
    color: 'from-teal-500 to-emerald-500',
    content: (
      <>
        <p>We strictly protect your commercial privacy. Data is disclosed only in the following limited circumstances:</p>
        <ul>
          <li><strong>Infrastructure Processors</strong> — Trusted cloud and payment infrastructure providers (MongoDB Atlas, Vercel, Render) strictly to the extent required to operate the Platform.</li>
          <li><strong>Statutory & Legal Requirements</strong> — When disclosure is formally required by an applicable court order, law enforcement directive, or statutory government mandate under Indian law.</li>
          <li><strong>Protection of Rights & Safety</strong> — To investigate security incidents, enforce our Terms & Conditions, or prevent fraud.</li>
          <li><strong>Business Transfers</strong> — In the event of a merger, acquisition, or restructuring, with advance notice provided to active account holders.</li>
        </ul>
      </>
    )
  },
  {
    id: 'third-party-services',
    num: '10',
    title: 'Third-Party Services Exclusions',
    icon: Globe,
    color: 'from-blue-500 to-cyan-500',
    content: (
      <>
        <p>To preserve data sovereignty and confidentiality, the Platform deliberately avoids unnecessary external integrations. We do <strong>not</strong> integrate with:</p>
        <ul>
          <li>Third-party advertising networks or marketing tracking networks.</li>
          <li>Third-party social media authentication trackers.</li>
          <li>External behavioral surveillance tools.</li>
        </ul>
      </>
    )
  },
  {
    id: 'financial-gst',
    num: '11',
    title: 'Financial & GST Data Handling',
    icon: FileText,
    color: 'from-emerald-500 to-green-500',
    content: (
      <>
        <ul>
          <li>The Platform is a <strong>software tool, not a certified accounting firm or statutory tax advisor</strong>.</li>
          <li>You are solely responsible for ensuring that product tax rates, HSN/SAC classifications, supplier GSTINs, customer GSTINs, and generated tax invoices comply with applicable GST legislation.</li>
          <li>The accuracy of tax summaries and reports depends entirely upon the rates, classifications, and entries configured by you.</li>
          <li>Customer payment entries recorded in the Platform are internal records entered by you; the Platform does not process external customer payments.</li>
        </ul>
        <div className="pp-callout pp-callout-warning">
          <strong>Notice:</strong> Always verify GST filings and statutory accounting records with a licensed Chartered Accountant or qualified tax advisor.
        </div>
      </>
    )
  },
  {
    id: 'employee-access',
    num: '12',
    title: 'Employee Access & Audit Accountability',
    icon: Users,
    color: 'from-orange-500 to-red-500',
    content: (
      <>
        <ul>
          <li><strong>Admin Authorization</strong> — Tenant Admins hold exclusive authority to create employee accounts and designate role-based module permissions.</li>
          <li><strong>Subordinate Access</strong> — Employee access is granted on behalf of the tenant Admin and does not confer personal ownership of tenant data.</li>
          <li><strong>Access Deactivation</strong> — Admins must promptly suspend or delete employee credentials when team members depart or reassign responsibilities.</li>
          <li><strong>Activity Logging</strong> — To safeguard business records against internal errors or disputes, employee actions (including purchase entries, invoice creation, and stock adjustments) may be logged with timestamps and user identifiers.</li>
        </ul>
      </>
    )
  },
  {
    id: 'data-security',
    num: '13',
    title: 'Data Security Measures & Limitations',
    icon: ShieldCheck,
    color: 'from-blue-500 to-blue-600',
    content: (
      <>
        <p>We deploy multiple layers of technical, administrative, and physical safeguards to protect your business information:</p>
        <ul>
          <li><strong>Encryption in Transit</strong> — All network communications between your browser and our servers are encrypted using modern Transport Layer Security (TLS/HTTPS).</li>
          <li><strong>Encryption at Rest</strong> — Data stored within MongoDB Atlas is encrypted using industry-standard disk encryption.</li>
          <li><strong>Password Protection</strong> — Passwords are hashed using bcrypt and are inaccessible even to our technical staff.</li>
          <li><strong>Logical Tenant Isolation</strong> — Authorization middleware verifies organization scope on every database transaction.</li>
          <li><strong>Vulnerability Management</strong> — Dependencies and software components are routinely patched and updated.</li>
        </ul>
        <div className="pp-callout pp-callout-warning">
          <strong>Security Notice:</strong> While we implement rigorous, industry-aligned security controls, no internet transmission or electronic cloud storage system can be guaranteed to be 100% impenetrable. We cannot promise absolute security against all unforeseen risks.
        </div>
      </>
    )
  },
  {
    id: 'user-rights',
    num: '14',
    title: 'Your Privacy Rights & Controls',
    icon: UserCheck,
    color: 'from-accent-500 to-accent-500',
    content: (
      <>
        <ul>
          <li><strong>Access & Review</strong> — You can access, review, and verify your business data, product catalog, customer records, supplier profiles, and transaction history directly within the Platform.</li>
          <li><strong>Correction & Updates</strong> — You can update or correct erroneous business or contact details via system interfaces.</li>
          <li><strong>Data Export</strong> — You may export reports, invoices, and summaries to standard spreadsheet or PDF formats for external archiving.</li>
          <li><strong>Account Closure</strong> — You may request complete account termination and data purge by contacting our support team.</li>
        </ul>
      </>
    )
  },
  {
    id: 'contact',
    num: '15',
    title: 'Privacy Contact & Support',
    icon: Mail,
    color: 'from-emerald-500 to-teal-500',
    content: (
      <>
        <p>If you have any questions, privacy inquiries, or requests regarding the processing of your data:</p>
        <div className="pp-table-wrap">
          <table>
            <tbody>
              <tr><td><strong>Platform</strong></td><td>Bharat Enterprise Billing System</td></tr>
              <tr><td><strong>Support Email</strong></td><td><a href="mailto:support.bharatenterprises@gmail.com" onClick={(e) => { const isMobile = /Mobi|Android|iPhone|iPad/i.test(navigator.userAgent); if (!isMobile) { e.preventDefault(); navigator.clipboard.writeText('support.bharatenterprises@gmail.com').then(() => { const el = document.getElementById('pp-email-copied'); if(el) { el.style.opacity='1'; setTimeout(()=> el.style.opacity='0', 2000); } }); } }} className="text-blue-400 hover:text-blue-300 transition-colors cursor-pointer" title="Click to copy or email">support.bharatenterprises@gmail.com</a> <span id="pp-email-copied" className="text-emerald-400 text-xs ml-2 transition-opacity duration-300" style={{opacity:0}}>✓ Copied!</span></td></tr>
              <tr><td><strong>Jurisdiction</strong></td><td>India</td></tr>
              <tr><td><strong>Response Window</strong></td><td>Within 7 business days</td></tr>
            </tbody>
          </table>
        </div>
      </>
    )
  }
];

export default function PrivacyPolicyPage() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="pp-page">
      {/* Background effects */}
      <div className="pp-bg-gradient pp-bg-gradient-1" />
      <div className="pp-bg-gradient pp-bg-gradient-2" />
      <div className="pp-bg-grid" />

      {/* Header */}
      <header className="pp-header">
        <div className="pp-header-inner">
          <Link to="/landing" className="pp-back-link">
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
          <div className="pp-header-content">
            <div className="pp-header-badge">
              <Shield className="w-4 h-4" />
              Privacy Document — Version 2.0.0
            </div>
            <h1 className="pp-title">Privacy Policy</h1>
            <p className="pp-subtitle">Bharat Enterprise Billing System</p>
            <p className="pp-last-updated">Last Updated: September 2, 2026</p>
          </div>
        </div>
      </header>

      {/* Table of Contents */}
      <nav className="pp-toc">
        <div className="pp-toc-inner">
          <h2 className="pp-toc-title">Table of Contents</h2>
          <div className="pp-toc-grid">
            {sections.map((s) => (
              <button
                key={s.id}
                onClick={() => document.getElementById(s.id)?.scrollIntoView({ behavior: 'smooth' })}
                className="pp-toc-link"
              >
                <span className="pp-toc-num">{s.num}</span>
                <span>{s.title}</span>
              </button>
            ))}
          </div>
        </div>
      </nav>

      {/* Sections */}
      <main className="pp-main">
        <div className="pp-main-inner">
          {sections.map((section) => (
            <section key={section.id} id={section.id} className="pp-section">
              <div className="pp-section-header">
                <div className={`pp-section-icon bg-gradient-to-br ${section.color}`}>
                  <section.icon className="w-5 h-5 text-white" />
                </div>
                <h2 className="pp-section-title">
                  <span className="pp-section-num">{section.num}.</span>
                  {section.title}
                </h2>
              </div>
              <div className="pp-section-body">
                {section.content}
              </div>
            </section>
          ))}

          {/* Summary Table */}
          <section className="pp-section pp-summary-section">
            <div className="pp-section-header">
              <div className="pp-section-icon bg-gradient-to-br from-blue-500 to-accent-500">
                <FileText className="w-5 h-5 text-white" />
              </div>
              <h2 className="pp-section-title">Quick Privacy Summary</h2>
            </div>
            <div className="pp-section-body">
              <div className="pp-table-wrap">
                <table>
                  <thead>
                    <tr>
                      <th>Topic</th>
                      <th>Summary</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr><td>Data Ownership</td><td>Tenant business data belongs exclusively to the organization (Admin).</td></tr>
                    <tr><td>Multi-Tenant Isolation</td><td>Strict logical isolation per tenant; zero cross-tenant access.</td></tr>
                    <tr><td>Supplier & Purchase Data</td><td>Processed strictly to maintain procurement records, vendor profiles, and inward stock.</td></tr>
                    <tr><td>Inventory & Movement Ledger</td><td>Stock movements (purchases, sales, returns) are tracked for operational visibility.</td></tr>
                    <tr><td>Employee Access & Audit</td><td>Granular permissions assigned by Admin; operational activity logged for accountability.</td></tr>
                    <tr><td>Payment Credentials</td><td>No card numbers or bank credentials stored; subscription billing secured via PCI-DSS compliant gateways.</td></tr>
                    <tr><td>GST & Tax Calculations</td><td>Tools compute estimates based on user inputs; user responsible for statutory compliance.</td></tr>
                    <tr><td>Third-Party Infrastructure</td><td>MongoDB Atlas (database), Vercel (frontend), Render (backend), secure payment gateways.</td></tr>
                    <tr><td>No External Trackers</td><td>No advertising pixels, social login trackers, or data reselling.</td></tr>
                    <tr><td>Data Retention</td><td>Retained during active subscription; historical data preserved across plan changes.</td></tr>
                    <tr><td>Security Standards</td><td>TLS encryption in transit, bcrypt password hashing, encryption at rest.</td></tr>
                  </tbody>
                </table>
              </div>
            </div>
          </section>
        </div>
      </main>

      {/* Footer */}
      <footer className="pp-footer">
        <div className="pp-footer-inner">
          <p>This Privacy Policy is effective as of September 2, 2026 (Version 2.0.0).</p>
          <p className="pp-footer-copyright">
            © {new Date().getFullYear()} Bharat Enterprise Billing System. All rights reserved.
          </p>
          <p className="pp-footer-love">
            Built with <Heart className="w-3 h-3 inline text-red-400 fill-red-400" /> in India
          </p>
          <Link to="/landing" className="pp-footer-home">
            ← Back to Home
          </Link>
        </div>
      </footer>
    </div>
  );
}
