import type { NextFunction, Response } from 'express';
const Product = require('../../models/Product');
const Admin = require('../../models/Admin');
const { getSearchPattern } = require('../../utils/searchUtils');
const getTenantId = require('../../utils/getTenantId');
import { ExportDefinition, ExportColumn } from '../../utils/export/types';
import { buildEffectiveStockAggregation } from '../../services/inventoryService';
import { buildWorkbook } from '../../utils/export/excel';
import { buildCSV } from '../../utils/export/csv';
import { buildPDF } from '../../utils/export/pdf';
import { sanitizeFilename } from '../../utils/export/helpers';

// Define the shape of our product data for the export
interface ProductExportRow {
  productName: string;
  manufacturer: string;
  hsnCode: string;
  gstPercentage: number;
  unit: string;
  rate: number;
  oldMRP: number;
  newMRP: number;
  currentStockQty: number;
  effectiveStockQty: number;
  inventoryRepresentation: string;
}

export const exportProducts = async (req: any, res: Response, next: NextFunction) => {
  try {
    const format = (req.query.format as string || 'excel').toLowerCase();
    const tenantId = getTenantId(req);
    
    // 1. Build Query (Matching getProducts)
    const query: any = { tenantId, isActive: true };
    const searchParam = req.query.search as string;
    
    if (searchParam) {
      const usePrefix = req.query.prefix === 'true';
      const pattern = getSearchPattern(searchParam, usePrefix);
      query.$or = [
        { productName: { $regex: pattern, $options: 'i' } },
        { hsnCode: { $regex: pattern, $options: 'i' } },
        { manufacturer: { $regex: pattern, $options: 'i' } }
      ];
    }
    
    // Fetch admin early for batch settings
    const admin = await Admin.findById(tenantId).lean();
    const enableBatchTracking = admin?.preferences?.enableBatchTracking === true;

    // Add stock filter via aggregation
    const aggregationPipeline: any[] = [
      { $match: query },
      ...buildEffectiveStockAggregation(tenantId, enableBatchTracking)
    ];

    const stockFilter = req.query.stockFilter as string;
    if (stockFilter === 'low') {
      aggregationPipeline.push({ $match: { effectiveStockQty: { $lte: 30, $gt: 0 } } });
    } else if (stockFilter === 'out') {
      aggregationPipeline.push({ $match: { effectiveStockQty: 0 } });
    }

    aggregationPipeline.push({ $sort: { createdAt: -1 } });

    // 2. Fetch Data
    const products = await Product.aggregate(aggregationPipeline);
    const totalRows = products.length;

    if (totalRows > 50000) {
      return res.status(400).json({
        success: false,
        message: 'Export exceeds the maximum supported size of 50,000 rows. Please apply additional filters.'
      });
    }
    
    if (totalRows === 0) {
      return res.status(404).json({
        success: false,
        message: 'No products found for export matching the criteria.'
      });
    }
    
    const firmName = admin?.firmName || 'Firm';
    
    // Setup Generated By Name
    let generatedBy = 'System User';
    if (req.user) {
      generatedBy = req.user.name || req.user.employeeName || req.user.adminName || req.user.username || 'User';
    }

    // 5. Data Mapping
    const dataRows: ProductExportRow[] = products.map((p: any) => ({
      productName: p.productName || '',
      manufacturer: p.manufacturer || '',
      hsnCode: p.hsnCode || '',
      gstPercentage: p.gstPercentage || 0,
      unit: p.unit || 'Pieces',
      rate: p.rate || 0,
      oldMRP: p.oldMRP || 0,
      newMRP: p.newMRP || 0,
      currentStockQty: p.currentStockQty || 0,
      effectiveStockQty: p.effectiveStockQty || 0,
      inventoryRepresentation: p.inventoryRepresentation || 'FREE'
    }));

    // 6. Calculate Business Metrics
    let totalStockUnits = 0;
    let inventoryValue = 0; // Value at Purchase Rate
    let totalGst = 0;
    const manufacturers = new Set<string>();

    dataRows.forEach(r => {
      totalStockUnits += r.effectiveStockQty;
      inventoryValue += r.effectiveStockQty * r.rate;
      totalGst += r.gstPercentage;
      if (r.manufacturer) manufacturers.add(r.manufacturer);
    });

    const averageGst = dataRows.length > 0 ? (totalGst / dataRows.length).toFixed(2) : '0';

    // 7. Define Export Contract
    const columns: ExportColumn<ProductExportRow>[] = [
      { key: 'productName', header: 'Product Name', width: 30 },
      { key: 'manufacturer', header: 'Manufacturer', width: 20 },
      { key: 'hsnCode', header: 'HSN Code', width: 15, align: 'center' },
      { key: 'gstPercentage', header: 'GST %', width: 10, align: 'center', format: 'percentage' },
      { key: 'unit', header: 'Unit', width: 15, align: 'center' },
      { key: 'rate', header: 'Purchase Rate', width: 15, format: 'currency' },
      { key: 'oldMRP', header: 'Old MRP', width: 15, format: 'currency' },
      { key: 'newMRP', header: 'New MRP', width: 15, format: 'currency' },
      { key: 'effectiveStockQty', header: 'Current Stock', width: 15, format: 'number' }
    ];

    const filters: Record<string, string> = {};
    if (searchParam) filters['Search Query'] = searchParam;
    if (stockFilter) filters['Stock Filter'] = stockFilter.toUpperCase();

    // 8. Dynamic Filename
    let baseFilename = 'Products';
    if (searchParam) baseFilename += `_${searchParam}`;
    else if (stockFilter) baseFilename += `_${stockFilter}`;
    
    const dateStr = new Date().toISOString().split('T')[0];
    baseFilename += `_${dateStr}`;
    const filename = sanitizeFilename(baseFilename);

    const exportDefinition: ExportDefinition<ProductExportRow> = {
      title: 'Product Inventory Report',
      filename,
      columns,
      dataRows,
      metadata: {
        firmName,
        generatedBy,
        generatedAt: new Date(),
        filters
      },
      summary: [
        { label: 'Total Products', value: dataRows.length, format: 'number' },
        { label: 'Total Inventory Units', value: totalStockUnits, format: 'number' },
        { label: 'Inventory Value (at Purchase Rate)', value: inventoryValue, format: 'currency' },
        { label: 'Average GST', value: averageGst, format: 'percentage' },
        { label: 'Unique Manufacturers', value: manufacturers.size, format: 'number' }
      ]
    };

    // 9. Dispatch to Engine
    if (format === 'excel') {
      const buffer = await buildWorkbook(exportDefinition);
      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}.xlsx"`);
      return res.send(buffer);
    } 
    else if (format === 'csv') {
      const csvData = buildCSV(exportDefinition);
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}.csv"`);
      return res.send(csvData);
    } 
    else if (format === 'pdf') {
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', `attachment; filename="${filename}.pdf"`);
      return buildPDF(exportDefinition, res);
    }

    return res.status(400).json({ success: false, message: 'Invalid export format. Supported: excel, csv, pdf' });

  } catch (error) {
    next(error);
  }
};
